-- =========================================
-- ANALYTICAL QUERIES (POSTGRESQL)
-- Retail Sales Data Pipeline
--
-- Purpose:
-- Demonstrate SQL reporting queries used to analyse
-- retail sales performance and support business
-- decision-making.
-- =========================================


-- =========================================
-- BUSINESS QUESTION
-- What is the total revenue generated?
--
-- BUSINESS PURPOSE
-- Helps management monitor overall sales
-- performance and track business growth.
--
-- REPORT OUTPUT
-- Total revenue generated from all sales.
-- =========================================

SELECT
    SUM(total_sales) AS total_revenue
FROM sales_clean;



-- =========================================
-- BUSINESS QUESTION
-- How does revenue change over time?
--
-- BUSINESS PURPOSE
-- Supports monthly performance reporting,
-- trend analysis and sales monitoring.
--
-- REPORT OUTPUT
-- Monthly revenue by year and month.
-- =========================================

SELECT
    order_year,
    order_month,
    SUM(total_sales) AS monthly_revenue
FROM sales_clean
GROUP BY order_year, order_month
ORDER BY order_year, order_month;



-- =========================================
-- BUSINESS QUESTION
-- Which products generate the highest revenue?
--
-- BUSINESS PURPOSE
-- Helps identify top-performing products and
-- supports product performance reporting.
--
-- REPORT OUTPUT
-- Top five products ranked by revenue.
-- =========================================

SELECT
    product_name,
    SUM(quantity) AS total_units_sold,
    SUM(total_sales) AS total_revenue
FROM sales_clean
GROUP BY product_name
ORDER BY total_revenue DESC
LIMIT 5;



-- =========================================
-- BUSINESS QUESTION
-- Which product categories contribute the
-- most revenue?
--
-- BUSINESS PURPOSE
-- Supports category performance reporting and
-- helps identify key revenue drivers.
--
-- REPORT OUTPUT
-- Revenue generated by each product category.
-- =========================================

SELECT
    category,
    SUM(total_sales) AS category_revenue
FROM sales_clean
GROUP BY category
ORDER BY category_revenue DESC;



-- =========================================
-- BUSINESS QUESTION
-- Which customers generated the highest
-- total sales value?
--
-- BUSINESS PURPOSE
-- Helps identify high-value customers and
-- supports customer performance reporting.
--
-- REPORT OUTPUT
-- Top five customers ranked by total spending.
-- =========================================

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(sc.total_sales) AS total_spent
FROM sales_clean AS sc
INNER JOIN customers AS c
    ON sc.customer_id = c.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_spent DESC
LIMIT 5;
